"use client";
import {useEffect,useState} from "react";
import {useParams,useSearchParams} from "next/navigation";
import {supabase} from "../../../../../lib/supabaseClient";
import {resolveControlledDocumentFileUrl} from "../../../../../lib/controlledDocumentStorage";
export default function DciFormalApprovalPage(){
 const {id}=useParams<{id:string}>();const sp=useSearchParams();const [dci,setDci]=useState<any>(null),[task,setTask]=useState<any>(null),[docs,setDocs]=useState<any[]>([]),[comment,setComment]=useState(""),[email,setEmail]=useState(""),[busy,setBusy]=useState(false),[impactRows,setImpactRows]=useState<any[]>([]),[additionalFiles,setAdditionalFiles]=useState<any[]>([]),[packageError,setPackageError]=useState("");
 const load=async()=>{const a=await supabase.auth.getUser();const me=String(a.data?.user?.email||"").trim().toLowerCase();setEmail(me);const taskId=sp.get("taskId");const [d,t,l]=await Promise.all([supabase.from("document_change_initiations").select("*").eq("id",id).single(),taskId?supabase.from("approval_tasks").select("*").eq("id",taskId).eq("assigned_to_email",me).eq("status","pending").maybeSingle():supabase.from("approval_tasks").select("*").eq("entity_type","document_change_initiation").eq("entity_id",id).eq("task_type","dci_formal_approval").eq("assigned_to_email",me).eq("status","pending").maybeSingle(),supabase.from("document_change_initiation_documents").select("document_id").eq("dci_id",id).order("sequence_no")]);if(d.error)return alert(d.error.message);setDci(d.data);setTask(t.data||null);const ids=(l.data||[]).map((x:any)=>x.document_id);if(ids.length){const [impactResult,fileResult]=await Promise.all([
 supabase.from("document_impact_assessments").select("document_id,impact_area,is_impacted,assessment,disposition_required,disposition_summary,assessed_by,assessed_at").eq("tenant_id",d.data.tenant_id).in("document_id",ids).order("impact_area"),
 supabase.from("document_change_document_files").select("id,document_id,file_name,file_path").eq("tenant_id",d.data.tenant_id).eq("dci_id",id).in("document_id",ids).order("created_at")
 ]);const errors:string[]=[];
 if(impactResult.error)errors.push("Impact Assessments: "+impactResult.error.message);else setImpactRows(impactResult.data||[]);
 if(fileResult.error)errors.push("Attachments: "+fileResult.error.message);else setAdditionalFiles(await Promise.all((fileResult.data||[]).map(async(file:any)=>({...file,url:await resolveControlledDocumentFileUrl({filePath:file.file_path}).catch(()=>null)}))));
 setPackageError(errors.join(" | "));
 const x=await supabase.from("controlled_documents").select("id,document_number,revision,title,document_type,file_name,file_path,file_url").in("id",ids);if(!x.error)setDocs(await Promise.all((x.data||[]).map(async(z:any)=>({...z,url:await resolveControlledDocumentFileUrl({filePath:z.file_path,legacyUrl:z.file_url}).catch(()=>z.file_url)}))));}};useEffect(()=>{if(id)load()},[id]);
 const decide=async(approve:boolean)=>{if(!task)return;if(!comment.trim())return alert("Approval comment is required.");if(!window.confirm(approve?"Approve this complete DCI package?":"Reject this complete DCI package?"))return;setBusy(true);try{const now=new Date().toISOString();const u=await supabase.from("approval_tasks").update({status:approve?"approved":"rejected",approver_comment:comment.trim(),signed_by:email,signed_at:now,signature_meaning:approve?"Approved DCI formal review":"Rejected DCI formal review",completed_at:now,completed_by_email:email}).eq("id",task.id);if(u.error)throw new Error(u.error.message);
 if(!approve){await supabase.from("approval_tasks").update({status:"cancelled",comments:"Formal review stopped because another approver rejected the DCI package."}).eq("entity_type","document_change_initiation").eq("entity_id",id).eq("task_type","dci_formal_approval").eq("status","pending");await supabase.from("document_change_initiations").update({status:"collaboration",updated_at:now}).eq("id",id);await supabase.from("approval_tasks").insert({entity_type:"document_change_initiation",entity_id:id,task_type:"dci_owner_finalization",task_title:`Resolve formal review rejection for ${dci.dci_number}`,required_function:"DCI Owner",assigned_to_email:String(dci.owner_email||"").toLowerCase(),assigned_by_email:email,status:"pending",comments:comment.trim(),record_number:dci.dci_number});}
 else{const remaining=await supabase.from("approval_tasks").select("id",{count:"exact",head:true}).eq("entity_type","document_change_initiation").eq("entity_id",id).eq("task_type","dci_formal_approval").eq("status","pending");if(!remaining.error&&(remaining.count||0)===0)await supabase.from("document_change_initiations").update({status:"formal_approved",updated_at:now}).eq("id",id);}
 await supabase.rpc("qualisphere_add_audit_log",{p_entity_type:"document_change_initiation",p_entity_id:id,p_action:approve?"formal_approval_approved":"formal_approval_rejected",p_details:`${email} ${approve?"approved":"rejected"} ${dci.dci_number}. Comment: ${comment.trim()}`});window.location.href="/workspace";
 }catch(e:any){alert(e.message||"Unable to record formal approval.");}finally{setBusy(false);}};
 if(!dci)return <main style={page}>Loading formal review...</main>;if(!task)return <main style={page}><h1>{dci.dci_number}</h1><p>No pending formal approval task is assigned to this account.</p><a href="/workspace">Back to My Workspace</a></main>;
 return <main style={page}><h1>{dci.dci_number} — Formal Approval</h1><p style={muted}>Your decision applies to the complete DCI package and every affected document.</p><section style={card}><h2>Change Package</h2><p><strong>Description:</strong> {dci.change_description||"—"}</p><p><strong>Justification:</strong> {dci.change_justification||"—"}</p></section><section style={card}><h2>Affected Documents &amp; Complete Review Package</h2><p style={muted}>Review each document, its primary markup, additional attachments, and Impact Assessment before making a decision on the entire DCI package.</p>
{packageError&&<p role="alert" style={{color:"#9f1d20"}}>Some package information could not be loaded: {packageError}</p>}
{docs.map(d=><details key={d.id} style={{...card,background:"#f8fafc",marginTop:12}}>
<summary style={{cursor:"pointer",fontWeight:800,fontSize:17,padding:"4px 0"}}>{d.document_number} Rev {d.revision} — {d.title}</summary>
<p style={muted}>{d.document_type||"Document"}</p>
<p><strong>Primary Markup / Redline: </strong>{d.url?<a href={d.url} target="_blank" rel="noreferrer">Open Primary File</a>:<span>Not attached</span>}</p>
<h4>Additional Files &amp; Attachments</h4>
{additionalFiles.filter(f=>f.document_id===d.id).length===0?<p style={muted}>No additional files attached.</p>:additionalFiles.filter(f=>f.document_id===d.id).map(f=><div key={f.id} style={item}>{f.url?<a href={f.url} target="_blank" rel="noreferrer">{f.file_name||"Open Attachment"}</a>:<span>{f.file_name||"Attachment"} — unavailable</span>}</div>)}
<details style={{marginTop:14}}><summary style={{cursor:"pointer",fontWeight:800}}>Impact Assessment — {impactRows.filter(a=>a.document_id===d.id).length} responses</summary>
{impactRows.filter(a=>a.document_id===d.id).length===0?<p style={muted}>No impact assessment responses found.</p>:impactRows.filter(a=>a.document_id===d.id).map((a,i)=><div key={a.impact_area+"-"+i} style={{...item,display:"block"}}><strong>{a.impact_area}</strong> — {a.is_impacted===true?"Impacted":a.is_impacted===false?"Not impacted":"Not assessed"}<p><strong>Assessment:</strong> {a.assessment||"—"}</p><p><strong>Disposition required:</strong> {a.disposition_required?"Yes":"No"}{a.disposition_summary?" — "+a.disposition_summary:""}</p></div>)}</details>
</details>)}</section><section style={card}><h2>Formal Decision</h2><textarea rows={5} style={textarea} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Approval/rejection comment (required)"/><div style={{display:"flex",gap:10}}><button style={primary} disabled={busy} onClick={()=>decide(true)}>Approve DCI Package</button><button style={danger} disabled={busy} onClick={()=>decide(false)}>Reject DCI Package</button></div></section></main>
}
const page:React.CSSProperties={padding:28,maxWidth:1100,margin:"0 auto",fontFamily:"Arial, sans-serif",background:"#f8fafc",minHeight:"100vh"};const muted:React.CSSProperties={color:"#64748b"};const card:React.CSSProperties={background:"#fff",border:"1px solid #d1d5db",borderRadius:12,padding:18,marginBottom:16};const item:React.CSSProperties={display:"flex",justifyContent:"space-between",gap:12,padding:12,border:"1px solid #e2e8f0",borderRadius:8,marginTop:8};const textarea:React.CSSProperties={width:"100%",boxSizing:"border-box",padding:10,border:"1px solid #cbd5e1",borderRadius:8,margin:"8px 0 14px"};const primary:React.CSSProperties={border:0,borderRadius:7,padding:"10px 14px",background:"#172033",color:"#fff",fontWeight:800};const danger:React.CSSProperties={...primary,background:"#fff",color:"#9f1d20",border:"1px solid #d8a1a3"};
