import { jsPDF } from "jspdf";
import { supabase } from "../lib/supabaseClient";

type ControlledDocument = {
  id: string;
  document_number: string;
  title: string;
  revision: string;
  status: string;
  effective_date: string | null;
  file_name: string | null;
  file_url: string | null;
  controlled_copy_file_name?: string | null;
  controlled_copy_file_path?: string | null;
  controlled_copy_file_url?: string | null;
};

function sanitizePathSegment(value: string | null | undefined) {
  return String(value || "document")
    .trim()
    .replace(/[^a-zA-Z0-9-_]/g, "_")
    .replace(/_+/g, "_");
}

function formatDate(value: string | null | undefined) {
  if (!value) return "N/A";
  try {
    return new Date(value).toLocaleDateString();
  } catch {
    return value;
  }
}

function addControlledCopyWatermark(pdf: jsPDF) {
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  pdf.setTextColor(210, 210, 210);
  pdf.setFontSize(44);
  pdf.setFont("helvetica", "bold");

  pdf.text("CONTROLLED COPY", pageWidth / 2, pageHeight / 2, {
    align: "center",
    angle: 35,
  });

  pdf.setTextColor(17, 24, 39);
  pdf.setFont("helvetica", "normal");
}

function addHeaderFooter({
  pdf,
  doc,
  pageNumber,
  totalPages,
}: {
  pdf: jsPDF;
  doc: ControlledDocument;
  pageNumber: number;
  totalPages: number;
}) {
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const effectiveDate = formatDate(doc.effective_date);

  pdf.setDrawColor(209, 213, 219);
  pdf.setLineWidth(0.4);
  pdf.line(15, 22, pageWidth - 15, 22);

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(10);
  pdf.text("QUALIFLOW ENTERPRISE - CONTROLLED COPY", 15, 12);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.text(`Document Number: ${doc.document_number}`, 15, 18);
  pdf.text(`Revision: ${doc.revision}`, pageWidth / 2 - 10, 18);
  pdf.text(`Effective Date: ${effectiveDate}`, pageWidth - 15, 18, {
    align: "right",
  });

  pdf.line(15, pageHeight - 18, pageWidth - 15, pageHeight - 18);
  pdf.setFontSize(8);
  pdf.text(
    `${doc.document_number} | Rev ${doc.revision} | Effective Date: ${effectiveDate}`,
    15,
    pageHeight - 10
  );
  pdf.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - 15, pageHeight - 10, {
    align: "right",
  });
}

function addWrappedText({
  pdf,
  text,
  x,
  y,
  maxWidth,
  lineHeight,
}: {
  pdf: jsPDF;
  text: string;
  x: number;
  y: number;
  maxWidth: number;
  lineHeight: number;
}) {
  const lines = pdf.splitTextToSize(text || "N/A", maxWidth);
  lines.forEach((line: string, index: number) => {
    pdf.text(line, x, y + index * lineHeight);
  });
  return y + lines.length * lineHeight;
}

export async function generateControlledCopy({
  documentId,
  generatedBy,
}: {
  documentId: string;
  generatedBy: string;
}) {
  if (!documentId) {
    throw new Error("Document ID is required to generate a controlled copy.");
  }

  const { data, error } = await supabase
    .from("controlled_documents")
    .select(
      "id, document_number, title, revision, status, effective_date, file_name, file_url, controlled_copy_file_name, controlled_copy_file_path, controlled_copy_file_url"
    )
    .eq("id", documentId)
    .maybeSingle();

  if (error) throw new Error(error.message);
  if (!data) throw new Error("Controlled document not found.");

  const doc = data as ControlledDocument;

  if (doc.status !== "effective") {
    throw new Error("Controlled copy can only be generated for effective documents.");
  }

  const pdf = new jsPDF({ unit: "mm", format: "letter" });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  addControlledCopyWatermark(pdf);
  addHeaderFooter({ pdf, doc, pageNumber: 1, totalPages: 1 });

  let y = 38;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  y = addWrappedText({
    pdf,
    text: doc.title || "Controlled Document",
    x: 15,
    y,
    maxWidth: pageWidth - 30,
    lineHeight: 8,
  });

  y += 8;

  pdf.setFontSize(11);
  pdf.text("Controlled Document Metadata", 15, y);
  y += 8;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);

  const rows = [
    ["Document Number", doc.document_number],
    ["Revision", doc.revision],
    ["Effective Date", formatDate(doc.effective_date)],
    ["Status", "CONTROLLED COPY"],
    ["Source File", doc.file_name || "N/A"],
    ["Generated By", generatedBy || "system"],
    ["Generated At", new Date().toLocaleString()],
  ];

  rows.forEach(([label, value]) => {
    pdf.setFont("helvetica", "bold");
    pdf.text(`${label}:`, 15, y);
    pdf.setFont("helvetica", "normal");
    pdf.text(String(value || "N/A"), 58, y);
    y += 7;
  });

  y += 8;
  pdf.setFont("helvetica", "bold");
  pdf.text("Controlled Copy Notice", 15, y);
  y += 7;

  pdf.setFont("helvetica", "normal");
  const notice =
    "This PDF represents the controlled copy record generated by QualiFlow Enterprise for the effective revision listed above. Approval signatures and approval metadata are maintained separately in the electronic signature record and workflow audit trail.";

  addWrappedText({
    pdf,
    text: notice,
    x: 15,
    y,
    maxWidth: pageWidth - 30,
    lineHeight: 6,
  });

  if (doc.file_url) {
    y = pageHeight - 34;
    pdf.setFont("helvetica", "bold");
    pdf.text("Source Document Link:", 15, y);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(37, 99, 235);
    pdf.textWithLink("Open source document", 55, y, { url: doc.file_url });
    pdf.setTextColor(17, 24, 39);
  }

  const safeDocNumber = sanitizePathSegment(doc.document_number);
  const safeRevision = sanitizePathSegment(doc.revision);
  const fileName = `${safeDocNumber}_Rev_${safeRevision}_Controlled_Copy.pdf`;
  const filePath = `controlled-copies/${safeDocNumber}/Rev-${safeRevision}/${fileName}`;

  const pdfBlob = pdf.output("blob");

  const { error: uploadError } = await supabase.storage
    .from("controlled-documents")
    .upload(filePath, pdfBlob, {
      contentType: "application/pdf",
      upsert: true,
    });

  if (uploadError) throw new Error(uploadError.message);

  const { data: publicUrlData } = supabase.storage
    .from("controlled-documents")
    .getPublicUrl(filePath);

  const controlledCopyUrl = publicUrlData?.publicUrl || null;

  const { error: updateError } = await supabase
    .from("controlled_documents")
    .update({
      controlled_copy_file_name: fileName,
      controlled_copy_file_path: filePath,
      controlled_copy_file_url: controlledCopyUrl,
      controlled_copy_generated_at: new Date().toISOString(),
      controlled_copy_generated_by: generatedBy || "system",
    })
    .eq("id", documentId);

  if (updateError) throw new Error(updateError.message);

  return {
    fileName,
    filePath,
    fileUrl: controlledCopyUrl,
  };
}
