"use client";

import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {supabase} from "../../../../../lib/supabaseClient";
import {resolveControlledDocumentFileUrl} from "../../../../../lib/controlledDocumentStorage";

export default function DciAdministrativeReviewPage(){
 const {id}=useParams<{id:string}>(); const [dci,setDci]=useState<any>(null),[task,setTask]=useState<any>(null),[docs,setDocs]=useState<any[]>([]),[approvers,setApprovers]=useState<any[]>([]),[users,setUsers]=useState<string[]>([]),[email,setEmail]=useState(""),[comment,setComment]=useState(""),[busy,setBusy]=useState(false),[newApprover,setNewApprover]=useState({email:"",dueDate:"",functionName:"",jobTitle:""}),[impactRows,setImpactRows]=useState<any[]>([]),[additionalFiles,setAdditionalFiles]=useState<any[]>([]);
 const load=async()=>{const a=await supabase.auth.getUser();const me=String(a.data?.user?.email||"").trim().toLowerCase();setEmail(me);
  const [d,t,links,q]=await Promise.all([supabase.from("document_change_initiations").select("*").eq("id",id).single(),supabase.from("approval_tasks").select("*").eq("entity_type","document_change_initiation").eq("entity_id",id).eq("task_type","dci_administrative_review").eq("status","pending").or(`assigned_to_email.eq.${me},assigned_to_email.is.null`).maybeSingle(),supabase.from("document_change_initiation_documents").select("document_id,change_type").eq("dci_id",id).order("sequence_no"),supabase.from("approval_tasks").select("id,assigned_to_email,status,due_date,approver_function,approver_job_title,required_function").eq("entity_type","document_change_initiation").eq("entity_id",id).eq("task_type","dci_formal_approval").in("status",["queued","pending"]).order("created_at")]);
  if(d.error)return alert(d.error.message);setDci(d.data);setTask(t.data||null);setApprovers(q.data||[]);const m=await supabase.from("tenant_memberships").select("user_email").eq("tenant_id",d.data.tenant_id).eq("membership_status","active").order("user_email");if(!m.error)setUsers((m.data||[]).map((x:any)=>String(x.user_email||"").trim().toLowerCase()).filter(Boolean));
  const ids=(links.data||[]).map((x:any)=>x.document_id);if(ids.length){
    const [impactResult,fileResult]=await Promise.all([
      supabase.from("document_impact_assessments").select("document_id,impact_area,is_impacted,assessment,disposition_required,disposition_summary,assessed_by,assessed_at").in("document_id",ids).eq("tenant_id",d.data.tenant_id).order("impact_area"),
      supabase.from("document_change_document_files").select("id,document_id,file_name,file_path").eq("dci_id",id).eq("tenant_id",d.data.tenant_id).in("document_id",ids).order("created_at")
    ]);
    if(impactResult.error)alert("Unable to load impact assessments: "+impactResult.error.message);else setImpactRows(impactResult.data||[]);
    if(fileResult.error)alert("Unable to load additional files: "+fileResult.error.message);
    else setAdditionalFiles(await Promise.all((fileResult.data||[]).map(async (file:any)=>({...file,url:await resolveControlledDocumentFileUrl({filePath:file.file_path}).catch(()=>null)}))));
const x=await supabase.from("controlled_documents").select("id,document_number,revision,title,document_type,file_name,file_path,file_url").in("id",ids);if(!x.error)setDocs(await Promise.all((x.data||[]).map(async(z:any)=>({...z,url:await resolveControlledDocumentFileUrl({filePath:z.file_path,legacyUrl:z.file_url}).catch(()=>z.file_url)}))));}
 };useEffect(()=>{if(id)load()},[id]);
 const claim=async()=>{if(!task||task.assigned_to_email)return;setBusy(true);try{const r=await supabase.rpc("qualisphere_claim_dci_administrative_review",{p_task_id:task.id});if(r.error)throw new Error(r.error.message);await load();}catch(e:any){alert(e.message||"Unable to claim task.");await load();}finally{setBusy(false);}};
 const addApprover=async()=>{if(!task?.assigned_to_email||task.assigned_to_email.toLowerCase()!==email)return alert("Claim the task before adjusting approvers.");if(!newApprover.email||!newApprover.dueDate||!newApprover.functionName.trim()||!newApprover.jobTitle.trim())return alert("Select an approver and due date.");if(approvers.some(a=>a.assigned_to_email===newApprover.email))return alert("This approver is already assigned.");const r=await supabase.from("approval_tasks").insert({entity_type:"document_change_initiation",entity_id:id,task_type:"dci_formal_approval",task_title:`Formal Approval for ${dci.dci_number}`,required_function:newApprover.functionName,approver_function:newApprover.functionName,approver_job_title:newApprover.jobTitle,assigned_to_email:newApprover.email,assigned_by_email:email,status:"queued",due_date:newApprover.dueDate,comments:"Queued pending Document Control administrative acceptance.",record_number:dci.dci_number});if(r.error)return alert(r.error.message);setNewApprover({email:"",dueDate:"",functionName:"",jobTitle:""});await load();};
 const removeApprover=async(taskId:string)=>{if(!window.confirm("Remove this formal approver?"))return;const r=await supabase.from("approval_tasks").update({status:"cancelled"}).eq("id",taskId).eq("status","queued");if(r.error)return alert(r.error.message);await load();};
 const updateDueDate=async(taskId:string,dueDate:string)=>{const r=await supabase.from("approval_tasks").update({due_date:dueDate}).eq("id",taskId).eq("status","queued");if(r.error)alert(r.error.message);else await load();};
 const decide=async(accept:boolean)=>{if(!task)return;if(!accept&&!comment.trim())return alert("Return reason is required.");if(!window.confirm(accept?"Accept the administrative check and send the DCI to formal approvers?":"Return the DCI to the owner for correction?"))return;setBusy(true);try{const now=new Date().toISOString();
  const done=await supabase.from("approval_tasks").update({status:"completed",completed_at:now,completed_by_email:email,completion_comment:comment.trim()||"Administrative and format check accepted."}).eq("id",task.id);if(done.error)throw new Error(done.error.message);
  if(accept){const q=await supabase.from("approval_tasks").update({status:"pending",comments:"Document Control administrative check accepted. Complete formal approval of the DCI package."}).eq("entity_type","document_change_initiation").eq("entity_id",id).eq("task_type","dci_formal_approval").eq("status","queued");if(q.error)throw new Error(q.error.message);const u=await supabase.from("document_change_initiations").update({status:"formal_review",updated_at:now}).eq("id",id);if(u.error)throw new Error(u.error.message);
   for(const a of approvers){await supabase.from("notifications").insert({user_email:a.assigned_to_email,assigned_role:"Formal Approver",notification_type:"dci_formal_approval",severity:"info",title:`Formal approval: ${dci.dci_number}`,message:"Document Control completed the administrative check. The DCI package is ready for formal approval.",related_module:"document_change_initiation",related_record_id:id,related_url:`/documents/changes/${id}`,read_status:false,created_by:email,delivery_frequency:"immediate",delivery_status:"in_app",deduplication_key:`document_change_initiation:${id}:formal_approval:${a.assigned_to_email}:${now}`});}
   await supabase.rpc("qualisphere_add_audit_log",{p_entity_type:"document_change_initiation",p_entity_id:id,p_action:"administrative_review_accepted",p_details:`${dci.dci_number} administrative check accepted by ${email}; formal approver tasks released.`});
  }else{await supabase.from("approval_tasks").update({status:"cancelled",comments:`Administrative check returned: ${comment.trim()}`}).eq("entity_type","document_change_initiation").eq("entity_id",id).eq("task_type","dci_formal_approval").eq("status","queued");const u=await supabase.from("document_change_initiations").update({status:"collaboration",updated_at:now}).eq("id",id);if(u.error)throw new Error(u.error.message);await supabase.from("approval_tasks").insert({entity_type:"document_change_initiation",entity_id:id,task_type:"dci_owner_finalization",task_title:`Finalize ${dci.dci_number} after Document Control return`,required_function:"DCI Owner",assigned_to_email:String(dci.owner_email||"").toLowerCase(),assigned_by_email:email,status:"pending",comments:comment.trim(),record_number:dci.dci_number});await supabase.rpc("qualisphere_add_audit_log",{p_entity_type:"document_change_initiation",p_entity_id:id,p_action:"administrative_review_returned",p_details:`${dci.dci_number} returned by Document Control. Reason: ${comment.trim()}`});}
  window.location.href="/workspace";
 }catch(e:any){alert(e.message||"Unable to complete administrative review.");}finally{setBusy(false);}};
 if(!dci)return <main style={page}>Loading administrative review...</main>;if(!task)return <main style={page}><h1>{dci.dci_number}</h1><p>No pending Document Control administrative task is available to this account.</p><a href="/workspace">Back to My Workspace</a></main>;
 return <main style={page}><header style={header}><div><div style={eyebrow}>DOCUMENT CONTROL ADMINISTRATIVE CHECK</div><h1>{dci.dci_number} — Administrative Review</h1><p style={muted}>Verify administrative and format readiness before releasing the complete DCI package to formal approvers.</p></div><a href="/workspace" style={secondary}>Back to My Workspace</a></header>
 {!task.assigned_to_email&&<section style={card}><h2>Shared Document Control Queue</h2><p style={muted}>This task is available to all active Document Control Coordinators. Claim it before performing the administrative review.</p><button style={primary} disabled={busy} onClick={claim}>{busy?"Claiming...":"Claim Task"}</button></section>}<section style={card}><h2>Change Package</h2><p><strong>Description:</strong> {dci.change_description||"—"}</p><p><strong>Justification:</strong> {dci.change_justification||"—"}</p></section>
 <section style={card}><h2>Affected Documents &amp; Complete Review Package</h2><p style={muted}>Review the primary markup, all additional attachments, and every impact-assessment response for each affected document.</p>
 {docs.map(d=><div key={d.id} style={{...card,background:"#f8fafc",marginTop:12}}>
 <h3>{d.document_number} Rev {d.revision} — {d.title}</h3><p style={muted}>{d.document_type||"Document"}</p>
 <p><strong>Primary Markup / Redline: </strong>{d.url?<a href={d.url} target="_blank" rel="noreferrer">Open Primary File</a>:<span>Not attached</span>}</p>
 <h4>Additional Files &amp; Attachments</h4>{additionalFiles.filter(f=>f.document_id===d.id).length===0?<p style={muted}>No additional files attached.</p>:additionalFiles.filter(f=>f.document_id===d.id).map(f=><div key={f.id} style={item}>{f.url?<a href={f.url} target="_blank" rel="noreferrer">{f.file_name||"Open Attachment"}</a>:<span>{f.file_name||"Attachment"} — unavailable</span>}</div>)}
 <h4>Impact Assessment</h4>{impactRows.filter(a=>a.document_id===d.id).length===0?<p style={muted}>No impact assessment responses found.</p>:impactRows.filter(a=>a.document_id===d.id).map((a,i)=><div key={a.impact_area+"-"+i} style={{...item,display:"block"}}><strong>{a.impact_area}</strong> — {a.is_impacted===true?"Impacted":a.is_impacted===false?"Not impacted":"Not assessed"}<p><strong>Assessment:</strong> {a.assessment||"—"}</p><p><strong>Disposition required:</strong> {a.disposition_required?"Yes":"No"}{a.disposition_summary?" — "+a.disposition_summary:""}</p></div>)}
 </div>)}</section>
 <section style={card}><h2>Formal Approvers</h2><p style={muted}>Review the owner's proposed approvers and due dates. Document Control may add, remove, or adjust them before formal review begins.</p>{approvers.map(a=><div key={a.id} style={item}><span><strong>{a.assigned_to_email}</strong><br/><small>Function: {a.approver_function||a.required_function||"—"} · Job Title: {a.approver_job_title||"—"}</small></span><span>Due: <input type="date" value={a.due_date||""} disabled={!task.assigned_to_email} onChange={e=>updateDueDate(a.id,e.target.value)}/></span><button style={secondary} disabled={!task.assigned_to_email} onClick={()=>removeApprover(a.id)}>Remove</button></div>)}{task.assigned_to_email&&<div style={{...item,alignItems:"end"}}><label>Function<input style={textarea} value={newApprover.functionName} onChange={e=>setNewApprover(v=>({...v,functionName:e.target.value}))}/></label><label>Job Title<input style={textarea} value={newApprover.jobTitle} onChange={e=>setNewApprover(v=>({...v,jobTitle:e.target.value}))}/></label><label>Approver<select style={textarea} value={newApprover.email} onChange={e=>setNewApprover(v=>({...v,email:e.target.value}))}><option value="">Select...</option>{users.filter(u=>u!==email&&!approvers.some(a=>a.assigned_to_email===u)).map(u=><option key={u}>{u}</option>)}</select></label><label>Due Date<input type="date" style={textarea} value={newApprover.dueDate} onChange={e=>setNewApprover(v=>({...v,dueDate:e.target.value}))}/></label><button style={secondary} onClick={addApprover}>+ Add Approver</button></div>}</section>
 <section style={card}><h2>Administrative Decision</h2><p style={muted}>Accept releases the queued formal-approval tasks. Return sends the package back to the DCI owner without repeating completed Collaboration.</p><textarea rows={5} style={textarea} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Administrative check notes; required when returning to owner."/><div style={{display:"flex",gap:10}}><button style={primary} disabled={busy||!task.assigned_to_email} onClick={()=>decide(true)}>Accept & Send to Formal Approvers</button><button style={danger} disabled={busy||!task.assigned_to_email} onClick={()=>decide(false)}>Return to DCI Owner</button></div></section></main>
}
const page:React.CSSProperties={padding:28,maxWidth:1200,margin:"0 auto",fontFamily:"Arial, sans-serif",background:"#f8fafc",minHeight:"100vh",color:"#0f172a"};const header:React.CSSProperties={display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start",flexWrap:"wrap",marginBottom:18};const eyebrow:React.CSSProperties={fontSize:12,fontWeight:900,letterSpacing:1.2,color:"#2563eb"};const muted:React.CSSProperties={color:"#64748b"};const card:React.CSSProperties={background:"#fff",border:"1px solid #d1d5db",borderRadius:12,padding:18,marginBottom:16};const item:React.CSSProperties={display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",padding:12,border:"1px solid #e2e8f0",borderRadius:8,marginTop:8};const textarea:React.CSSProperties={width:"100%",boxSizing:"border-box",padding:10,border:"1px solid #cbd5e1",borderRadius:8,margin:"8px 0 14px"};const primary:React.CSSProperties={border:0,borderRadius:7,padding:"10px 14px",background:"#172033",color:"#fff",fontWeight:800,cursor:"pointer"};const danger:React.CSSProperties={...primary,background:"#fff",color:"#9f1d20",border:"1px solid #d8a1a3"};const secondary:React.CSSProperties={border:"1px solid #cbd5e1",borderRadius:7,padding:"9px 12px",background:"#fff",color:"#172033",fontWeight:800,textDecoration:"none"};
